### PR TITLE
Add error handling to processing on line 310

### PR DESCRIPTION
**Pull request by SOGAKEN**
I get an error when starting inkdrop because I can't get the _userid. Added error handling in that area.

### CODE REVIEW

**Comment by fredluetkemeier** [comment]
Hey, thanks for the PR! 

I'm wondering if there's a graceful way we can handle this. I think it's good that we're printing out the error with `console.error`, but I would really like to know why `_userid` is missing in the first place.

If you're still getting this error, would you mind posting what your `inkdrop.main.account` object looks like? Just curious if the user id property has been moved somewhere else with the latest update. 

Thanks!

**Comment by SOGAKEN** [comment]
Hello.

Without this error handling, the initial read will fail and then the process will not work.

Perhaps the structure has not changed, but the behavior of the application at startup may have changed.

**Comment by fredluetkemeier** [comment]
> Without this error handling, the initial read will fail and then the process will not work.

Does reloading the application work? Or does it fail each time the application starts? 

Unfortunately I'm unable to reproduce the issue, so some more information about your setup and issue would really be helpful. Thanks!

**Comment by fredluetkemeier** [comment]
After doing some more digging it looks like the `account` object under `inkdrop.main` is gone. This means that this function will never yield a valid hashed id. 

Closing this since I think we need a deeper solution. Hopefully I can push a fix relatively soon.

**Comment by fredluetkemeier** [comment]
After doing some more digging it looks like the account object under inkdrop.main is gone. This means that this function will never yield a valid hashed id.

Closing this since I think we need a deeper solution. Hopefully I can push a fix relatively soon.

**Pull request closed without merging**
